### ISSUE TITLE
There is an existing tool called Bloaty McBloatface

### ISSUE THREAD

**Issue by haberman** [jrieken/ts-unused#1]
Hi there! I just happened to be Googling for "Bloaty McBloatface" today (random vanity Google) and came across your project. I don't know if you knew, but I released a tool under this name about a year ago: http://blog.reverberate.org/2016/11/07/introducing-bloaty-mcbloatface.html

I don't mean to bother you if this is just something you're playing around with. But if you mean to release this as a tool to the wider world, the name conflict would probably be confusing.

**Comment by jrieken** [comment]
Oh, I didn't know that... The repo is called `ts-unused` because it's just there to find unused symbols in TypeScript projects. The 'Bloaty McBloatface' was just me being silly and nothing I have mean to use a name. I'll tweak the README-file
